SELECT * FROM GENRES;
SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;

SELECT * FROM AUTHORS WHERE AUTHORS.ID = 2;
SELECT * FROM AUTHORS WHERE AUTHORS.LASTNAME = 'Cruiser';

SELECT * FROM BOOKS, GENRES WHERE GENRE_ID = GENRES.ID;

SELECT FIRSTNAME, LASTNAME, TITLE, GENRE_NAME FROM AUTHORS, BOOKS, GENRES WHERE GENRE_ID = GENRES.ID AND AUTHOR_ID = AUTHORS.ID;

SELECT FIRSTNAME, LASTNAME, TITLE, GENRE_NAME FROM AUTHORS, BOOKS, GENRES WHERE AUTHORS.LASTNAME = 'Cruiser' AND GENRE_ID = GENRES.ID AND AUTHOR_ID = AUTHORS.ID;





