FROM openjdk:11
RUN mkdir -p /opt/Spring_Training_2
WORKDIR /opt/Spring_Training_2
COPY /target/SpringTraining-0.0.1-SNAPSHOT.jar /opt/Spring_Training_2
CMD ["java", "-jar", "SpringTraining-0.0.1-SNAPSHOT.jar"]